version: '3.8'

services:
  # Event Bus Service
  event-bus:
    build: ./event-bus
    volumes:
      - ./event-bus:/app
      - /app/node_modules
    ports:
      - "4005:4005"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=secret
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=event_db
      - DB_USER=postgres
      - DB_PASSWORD=pass
    networks:
      - microservice-net
    depends_on:
      postgres:
        condition: service_healthy

  user-mgmt-service:
    build: ./user-mgmt-service
    volumes:
      - ./user-mgmt-service:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - EVENT_BUS_URL=http://event-bus:4005
      - JWT_SECRET=secret
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=user_db
      - DB_USER=postgres
      - DB_PASSWORD=pass
    networks:
      - microservice-net
    depends_on:
      postgres:
        condition: service_healthy
      event-bus:
        condition: service_started

  review-request-service:
    build: ./review-request-service
    volumes:
      - ./review-request-service:/app
      - /app/node_modules
    ports:
      - "4003:4003"
    environment:
      - EVENT_BUS_URL=http://event-bus:4005
      - JWT_SECRET=secret
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=review_db
      - DB_USER=postgres
      - DB_PASSWORD=pass
    networks:
      - microservice-net
    depends_on:
      event-bus:
        condition: service_started
      postgres:
        condition: service_healthy

  post-grades-service:
    build: ./post-grades-service
    volumes:
      - ./post-grades-service:/app
      - /app/node_modules
    ports:
      - "4001:4001"
    environment:
      - EVENT_BUS_URL=http://event-bus:4005
      - JWT_SECRET=secret
      - NODE_ENV=development
      - DB_HOST=postgres 
      - DB_PORT=5432
      - DB_NAME=grades_db
      - DB_USER=postgres
      - DB_PASSWORD=pass
    networks:
      - microservice-net
    depends_on:
      event-bus:
        condition: service_started
      postgres:
        condition: service_healthy

  course-service:
    build: ./course-service
    volumes:
      - ./course-service:/app
      - /app/node_modules
    ports:
      - "4004:4004"
    environment:
      - EVENT_BUS_URL=http://event-bus:4005
      - JWT_SECRET=secret
      - NODE_ENV=development
      - DB_HOST=postgres 
      - DB_PORT=5432
      - DB_NAME=course_db
      - DB_USER=postgres
      - DB_PASSWORD=pass
    networks:
      - microservice-net
    depends_on:
      event-bus:
        condition: service_started
      postgres:
        condition: service_healthy

  analytics-service:
    build: ./analytics-service
    volumes:
      - ./analytics-service:/app
      - /app/node_modules
    ports:
      - "4002:4002"
    environment:
      - EVENT_BUS_URL=http://event-bus:4005
      - JWT_SECRET=secret
      - NODE_ENV=development
      - DB_HOST=postgres 
      - DB_PORT=5432
      - DB_NAME=analytics_db
      - DB_USER=postgres
      - DB_PASSWORD=pass
    networks:
      - microservice-net
    depends_on:
      event-bus:
        condition: service_started
      postgres:
        condition: service_healthy

  # Frontend Service
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - EVENT_BUS_URL=http://event-bus:4005
    networks:
      - microservice-net
    depends_on:
      - event-bus

  # PostgreSQL (shared)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_MULTIPLE_DATABASES=event_db,user_db,review_db,grades_db,course_db,analytics_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5433:5432"
    networks:
      - microservice-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  microservice-net:
    driver: bridge

volumes:
  postgres_data:
